- name: Catalogue
  hosts: catalogue
  become: yes
  tasks:
    - name: Enable nodejs 18
      ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y
    
    - name: Install NodeJS
      ansible.builtin.dnf:
        name: nodejs
        state: present
    
    - name: user add
      ansible.builtin.user:
        name: roboshop

    - name: Create app directory
      ansible.builtin.file:
        path: /app
        state: directory
    
    - name: Download catalogue directory files
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
        dest: /tmp
    
    # - name: This command will change the working directory to app/
    #   ansible.builtin.shell:
    #   args:
    #     chdir: /app

    - name: Unarchive/Unzip a file that is already on the catalogue/remote machine
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app
        remote_src: yes

    # - name: download/install the dependencies
    #   ansible.builtin.package:
    #     name: npm
    #     state: present

    - name: download/install the dependencies
      ansible.builtin.command: npm install
      args:
        chdir: /app
    
    - name: setup/copy catalogue service
      ansible.builtin.copy:
        src: catalogue.service
        dest: /etc/systemd/system/catalogue.service



    - name: reload the catalogue daemon
      ansible.builtin.systemd_service:
        daemon_reload: true
        name: catalogue

    - name: Setup/Copy the MongoDB repo file
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: insall mongodb org shell client
      ansible.builtin.dnf:
        name: mongodb-org-shell
        state: present

    - name: get the catagories count
      ansible.builtin.command: mongo --host 54.234.195.75 --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
      register: product_count

    - name: print product count just reference
      ansible.builtin.debug:
        msg: '{{product_count}}'

    - name: load catalogue to mongodb server
      ansible.builtin.command: mongo --host 54.234.195.75 < /app/schema/catalogue.js
      when: product_count.stdout == "0"

    - name: Enable/reload catalogue service
      ansible.builtin.service:
        name: catalogue
        state: started
        enabled: true