- name: Catalogue
  hosts: catalogue
  become: yes
  tasks:
    - name: Enable nodejs 18
      ansible.builtin.command: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y
    
    - name: Install NodeJS
      ansible.builtin.dnf:
        name: nodejs
        state: present
    
    - name: user add
      ansible.builtin.command: useradd roboshop

    - name: Create app directory
      ansible.builtin.file:
        path: ~/app
        state: directory
    
    - name: Download catalogue directory files
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
        dest: ~/app
    
    - name: This command will change the working directory to app/
      ansible.builtin.shell:
      args:
        chdir: app/

    - name: Unarchive/Unzip a file that is already on the catalogue/remote machine
      ansible.builtin.unarchive:
        src: ~/app/catalogue.zip
        dest: /tmp/

    - name: download the dependencies
      ansible.builtin.package:
        name: npm
        state: present
    
    - name: reload the catalogue daemon
      ansible.builtin.systemd_service:
        name: catalogue
        state: reloaded
      
    - name: Enable mongodb service
      ansible.builtin.service:
        name: catalogue
        state: started
        enabled: true
      
    - name: setup/copy MongoDB repo
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d

    - name: insall mongodb org shell
      ansible.builtin.dnf:
        name: mongodb-org-shell
        state: present

