- name: Catalogue
  hosts: catalogue
  become: yes
  tasks:
    - name: Enable nodejs 18
      ansible.builtin.command: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y
    
    - name: Install NodeJS
      ansible.builtin.dnf:
        name: nodejs
        state: present
    
    # - name: user add
    #   ansible.builtin.command: useradd roboshop
        
