- name: MYSQL configuration
  hosts: mysql
  become: yes
  tasks:
    - name: Disable mysql module
      ansible.builtin.shell: dnf module disable mysql -y
  
    - name: Setup/Copy the MSSQL repo file
      ansible.builtin.copy:
        src: mysql.repo
        dest: /etc/yum.repos.d/mysql.repo

    - name: mysql-community-server install
      ansible.builtin.package:
        name: mysql-community-server
        state: present
    
    - name: Enable mysqld service
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: true
    
    - name: MYSQL root password change
      ansibl.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1

