- name: replace values in file
  hosts: localhost
  become: yes
  tasks: 
  - name: Replace value in file
    lineinfile:
      path: example.conf
      regexp: '^{{item.key}}:'
      line: "{{item.key}}: {{item.value}}"
    with_dict: {name: Michael, age: 31, city: San Francisco}