- name: web page configuration
  hosts: web
  become: true
  tasks:
    - name: Install nginx
      ansible.builtin.package:
        name: nginx
        state: present
  
    # -name: 

    - name: Remove files from html folder
      ansisble.builtin.file:
      find:
        path: /usr/share/nginx/html/
        state: absent
      register: cleanup


  # - name: Removing all files previously found in files dir
  #   file:
  #     path: "{{ item.path }}"
  #     state: absent
  #   with_items: "{{ cleanup.files }}"
  #   ignore_errors: true