- name: web page configuration
  hosts: web
  become: true
  tasks:
    - name: Install nginx
      ansible.builtin.package:
        name: nginx
        state: present
  
    # -name: 

  - name: Locating all files in files dir
    find:
      path: "{{ /usr/share/nginx/html/ }}/files"
    register: cleanup
    ignore_errors: true

  # - name: Removing all files previously found in files dir
  #   file:
  #     path: "{{ item.path }}"
  #     state: absent
  #   with_items: "{{ cleanup.files }}"
  #   ignore_errors: true